# Generated by Django 4.0.2 on 2022-02-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Posiłek')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Waga')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Kalorie')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Białko')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Węglowodany')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tłuszcze')),
                ('genre', models.IntegerField(choices=[(0, 'Śniadanie'), (1, 'Obiad'), (2, 'Kolacja'), (3, 'Przekąska')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desirable_intake', models.IntegerField(choices=[(1000, '1000'), (1100, '1100'), (1200, '1200'), (1300, '1300'), (1400, '1400'), (1500, '1500'), (1600, '1600'), (1700, '1700'), (1800, '1800'), (1900, '1900'), (2000, '2000'), (2100, '2100'), (2200, '2200'), (2300, '2300'), (2400, '2400'), (2500, '2500'), (2600, '2600'), (2700, '2700'), (2800, '2800'), (2900, '2900'), (3000, '3000')], default=0, verbose_name='Dzienna liczba kalorii')),
                ('daily_calories', models.FloatField(blank=True, null=True)),
                ('foods', models.ManyToManyField(to='Calculator.FoodItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
