# Generated by Django 4.0.2 on 2022-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_carbs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_fats', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
